soda/urls.py
from django.contrib import admin
from django.urls import path, include

from soda_beta import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sodabeta/', include('soda_beta.urls')),
    path('', views.MainView.as_view(), name='home'),
]

#1:현재 마이그레이션 안함, db 다른거 쓰기 때문에 최초로 생성할 필요가 없어서,,,기본 유저 정보 만들어진다. 편리하게 관리할 수 있는 페이지가 만들어진다.
#3:처음 ''치면 홈페이지 나와라
#2:sodabeta > urls.py의 qahelper로 들어가면 연결되도록 한다.그래서 도메인 다음에 붙고 나서, 실행

soda_beta/urls.py
from django.urls import path

from soda_beta import views, _ajax

app_name = 'soda_beta'
urlpatterns = [

    path('qahelper/<slug:type>', views.QAHelperView.as_view(), name='qa_helper'),
    path('<slug:app>/style', views.StyleView.as_view(), name='app_style'),
    path('ajax/api/style', _ajax.call_style_api, name='api_style')
    ]

# 메인 홈 > QAHelperView를 추가함. 이렇게 설정하는 방법들은 정규식으로도 할 수 있고,
#정규식은 숫자를 OR/AND 개념으로 => 참고 : https://wayhome25.github.io/django/2017/03/18/django-ep2-regx/
# 함수형 뷰

soda_beta/models.py
from django.db import models

# Create your models here.
class Information(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'global_information'

class Makeup(models.Model):
    builtin_id = models.IntegerField(null=True, blank=True)
    type = models.CharField(max_length=10, null=False, blank=False)
    makeup_name = models.CharField(max_length=255, null=False, blank=False)
    name = models.CharField(max_length=255, null=False, blank=False)
    sub_name = models.TextField(null=True, blank=True)
    class Meta:
        db_table = 'makeup'

"""
builtin_id           int          null,
    type                 varchar(10)  not null,
    makeup_name          varchar(255) null,
    name                 varchar(255) not null,
    sub_name             text         null,
    thumbnail            varchar(255) null,
    thumbnail_color      varchar(20)  null,
    version              bigint       not null,
    screen_capture_mode  bit          not null,
    download_type        varchar(255) not null,
    device_types         varchar(20)  null,
    min_ios_version      varchar(20)  null,
    max_ios_version      varchar(20)  null,
    min_android_version  varchar(20)  null,
    max_android_version  varchar(20)  null,
    newmark_end_date     datetime     null,
    designated_countries text         null,
    banned_countries     text         null,
    sale                 bit          not null,
    package_json         text         null,
    for_marketing        bit          null,
    orderz               int          null,
    updated              datetime     not null,
    created              datetime     not null,
    admin                varchar(20)  null
"""

soda_beta/views.py
import requests
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from soda_beta.models import Information, Makeup


class MainView(TemplateView):
    template_name = 'soda_beta/helper_main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        # 장고는 아래의 함수로 쿼리를 알아서 생성 및 실행하고 모델에 담아준다.
        #obj = Makeup.objects.filter(builtin_id=3001)
        # 장고는 또 raw를 써서 쿼리를 날려주고, 모델에 담아준다.
        #obj = Makeup.objects.raw("SELECT id,type FROM makeup WHERE builtin_id=3001")
        #context['model'] = obj
        #Information.objects.raw('SELECT "name" from ')
        return context


class StyleView(TemplateView):
    template_name = 'soda_beta/helper_style.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return context
    def get(self, request, app, *args, **kwargs):
        context = self.get_context_data()
        context['app'] = app
        return self.render_to_response(context=context)

class QAHelperView(TemplateView):
    template_name = 'soda_beta/soda_qahelper.html'

    """ TemplateView
    template_name이라는 것 자체가 부모가 가지고 있는 것, 장고는 굉장히 많이 상속을 한다.
   detail view, list view 개념 참고 : https://citylock77.tistory.com/66
   """



    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        # 장고는 아래의 함수로 쿼리를 알아서 생성 및 실행하고 모델에 담아준다.
        #obj = Makeup.objects.filter(builtin_id=3001)
        # 장고는 또 raw를 써서 쿼리를 날려주고, 모델에 담아준다.
        #obj = Makeup.objects.raw("SELECT id,type FROM makeup WHERE builtin_id=3001")
        #context['model'] = obj
        #Information.objects.raw('SELECT "name" from ')
        return context
    def get(self, request, type, *args, **kwargs):
        context = self.get_context_data()
        #res = requests.get('http://qa-content-b612-api.snow.me/v1/text/overview')
        context['type'] = type

        return self.render_to_response(context)

    # 저장할때 보통 POST쓰고, page를 보통 load 하는것이 get
    # 보통 위와 같이 쓴다. 중간 과정에서 데이터를 주고받음

def qahelper(request):
    if request.method == "POST":
        data = request.POST.get('gender')
        #데이터를 얻었다 -> 거기에 저장할 때 이름으로 데이터를 저장해서 전달한다. 프론트엔드에서 정하고 백엔드에서 알고 있어야 한다.
        return render(request)
    #쌩으로 동작 시켜주는 것이 request, 그래서 페이지가 확실히 구분되어 불러올 때 함수형쓰고, 페이지 내부에서 ajax를 쓰거나 한다.
    #render 쫓아가 보면 다 구조화 시켜줬다.


#

helperapp/templates/helperapp/helper_filter.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
        <meta http-equiv="Pragma" content="no-cache">
        <meta charset="UTF-8">
        <title>QAHelper</title>
        <link rel="stylesheet" href="{% static 'css/helper_main.css'%}">
<!--        <link rel="stylesheet" href="./css/helper_main.css">-->
        <link rel="stylesheet" href="{% static 'css/helper_style.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_filter.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_studio.css'%}">

        <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
    </head>
    <body>
        <div class="pageTitle">
            SODA/Tianyan QAHelper
        </div>
        <div class="mainContainer">
            <div class="mainTitle">
                Filter
            </div>
            <div class="showSchemeContainer">
                <div class="showSchemeRow">
                    <input type="text" size="150px" />
                    현재 스킴 실시간 보여주는 영역
                </div>
                <div class="qrcodeRow">
                    <button type="button">
                        QR Code
                    </button>
                </div>
            </div>
            <div class="showQrcodeColumn">
                <!-- QR Code 들어오는 자리 -->
                <img src="{% static 'image/qr_ex.png' %}" width="200px" height="200px">
            </div>
            <hr size="2" width="100%" color="black">
            <div class="schemeListContainer">
                <div class="schemeAutoDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/autoDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeManualDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/manualDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeInCameraBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/inCameraBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeOutCameraBtnRow">
                   <button type="button" class="btnSetting">
                       <img src="{% static 'image/outCameraBtn.png' %}" width="100px" height="100px" />
                   </button> 
                </div>
            </div>
            <hr size="2" width="100%" color="black">
            <div class="insertIdContainer">
                <div class="insertIdRow">
                    <input type="text" size="20px" />
                    Filter Id 입력 부분
                </div>
                <div class="addIdRow">
                    <button type="button">
                        Add ID
                    </button>
                </div>
            </div>
            <div class="contentsListContainer">
                필터 리스트 노출 영역
                <div class="categoryNameColumn">
                    카테고리 이름 노출 영역
                </div>
                <div class="showContentsContainer">
                    <div class="contentsIdColumn">
                        <컨텐츠 ID 노출 영역>
                    </div>
                    <div class="contentsThumbnailColumn">
                        컨텐츠 썸네일 노출 영역
                    </div>
                    <div class="contentsNameColumn">
                        <컨텐츠 이름 노출 영역>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

helperapp/templates/helperapp/helper_studio.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
        <meta http-equiv="Pragma" content="no-cache">
        <meta charset="UTF-8">
        <title>QAHelper</title><link rel="stylesheet" href="{% static 'css/helper_main.css'%}">
<!--        <link rel="stylesheet" href="./css/helper_main.css">-->
        <link rel="stylesheet" href="{% static 'css/helper_style.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_filter.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_studio.css'%}">

        <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
    </head>
    <body>
        <div class="pageTitle">
            SODA/Tianyan QAHelper
        </div>
        <div class="mainContainer">
            <div class="mainTitle">
                Studio
            </div>
            <div class="showSchemeContainer">
                <div class="showSchemeRow">
                    <input type="text" size="150px" />
                    현재 스킴 실시간 보여주는 영역
                </div>
                <div class="qrcodeRow">
                    <button type="button">
                        QR Code
                    </button>
                </div>
            </div>
            <div class="showQrcodeColumn">
                <!-- QR Code 들어오는 자리 -->
                <img src="{% static 'image/qr_ex.png' %}" width="200px" height="200px">
            </div>
            <hr size="2" width="100%" color="black">
            <div class="insertIdContainer">
                <div class="insertIdRow">
                    <input type="text" size="20px" />
                    스튜디오 템플릿 Id 입력 부분
                </div>
                <div class="studioAddIdRow">
                    <button type="button">
                        Add ID
                    </button>
                </div>
            </div>
            <hr size="2" width="100%" color="black">
            <div class="studioCategoryContainer">
                <div class="studioCategoryRow">
                    스튜디오 템플릿 카테고리 노출 영역
                </div>
            </div>
            <hr size="2" width="100%" color="black">
            <div class="studioContentsContainer">
                스튜디오 템플릿 리스트 노출 영역
                <div class="studioShowContentsContainer">
                    <div class="studioTemplateIdColumn">
                        스튜디오 템플릿 ID 노출 영역
                    </div>
                    <div class="studioStyleIdColumn">
                        템플릿의 스타일 ID 노출 영역
                    </div>
                    <div class="studioThumbnailColumn">
                        스튜디오 템플릿 썸네일 노출 영역
                    </div>
                    <div class="studioNameColumn">
                        스튜디오 템플릿 이름 노출 영역
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

helperapp/templates/helperapp/helper_style.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
        <meta http-equiv="Pragma" content="no-cache">
        <meta charset="UTF-8">
        <title>QAHelper</title>
        <link rel="stylesheet" href="{% static 'css/helper_main.css'%}">
<!--        <link rel="stylesheet" href="./css/helper_main.css">-->
        <link rel="stylesheet" href="{% static 'css/helper_style.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_filter.css'%}">
        <link rel="stylesheet" href="{% static 'css/helper_studio.css'%}">

        <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
    </head>
    <body>
        <div class="pageTitle">
            SODA/Tianyan QAHelper
        </div>
        <div class="mainContainer">
            <div class="mainTitle">
                Style
            </div>
            <div class="showSchemeContainer">
                <div class="showSchemeRow">
                    <input type="text" size="150px" />
                    현재 스킴 실시간 보여주는 영역
                </div>
                <div class="qrcodeRow">
                    <button type="button">
                        QR Code
                    </button>
                </div>
            </div>
            <div class="showQrcodeColumn">
                <!-- QR Code 들어오는 자리 -->
                <img src="{% static 'image/qr_ex.png' %}" width="200px" height="200px">
            </div>
            <hr size="2" width="100%" color="black">
            <div class="schemeListContainer">
                <div class="schemeAutoDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/autoDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeManualDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/manualDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeInCameraBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'image/inCameraBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeOutCameraBtnRow">
                   <button type="button" class="btnSetting">
                       <img src="{% static 'image/outCameraBtn.png' %}" width="100px" height="100px" />
                   </button> 
                </div>
            </div>
            <hr size="2" width="100%" color="black">
            <div class="insertIdContainer">
                <div class="insertIdRow">
                    <input type="text" size="20px" />
                    Style Id 입력 부분
                </div>
                <div class="addIdRow">
                    <button type="button">
                        Add ID
                    </button>
                </div>
            </div>
            <div class="contentsListContainer">
                스타일 리스트 노출 영역
                <div class="categoryNameColumn">
                    카테고리 이름 노출 영역
                </div>
                <div class="showContentsContainer">
                    <div class="contentsIdColumn">
                        <컨텐츠 ID 노출 영역>
                    </div>
                    <div class="contentsThumbnailColumn">
                        컨텐츠 썸네일 노출 영역
                    </div>
                    <div class="contentsNameColumn">
                        <컨텐츠 이름 노출 영역>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>title</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <!-- 합쳐지고 최소화된 최신 CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- 부가적인 테마 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>
{% block navbar %}

{% endblock %}

<div id="main">
    {% block main %}

    {% endblock %}
</div>
</body>
</html>

templates/soda_beta/helper_filter.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <link rel="filtersheet" href="{% static 'css/scheme/helper_filter.css' %}">
    <script src="{% static 'js/scheme/helper_filter.js' %}"></script>
        <div class="pageTitle">
            SODA/Tianyan QAHelper
        </div>
        <div class="mainContainer">
            <div class="mainTitle">
                Filter
            </div>
            <div class="showSchemeContainer">
                <div class="showSchemeRow">
                    <input type="text" size="150px" id="scheme_input" />
                    현재 스킴 실시간 보여주는 영역
                </div>
                <div class="qrcodeRow">
                    <button type="button">
                        QR Code
                    </button>
                </div>
            </div>
            <div class="showQrcodeColumn">
                <!-- QR Code 들어오는 자리 -->
                <img src="./qr_ex.png" width="200px" height="200px">
            </div>
            <hr size="2" width="100%" color="black">
            <div class="schemeListContainer">
                <div class="schemeAutoDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'images/main/autoDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeManualDlBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'images/main/manualDlBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeInCameraBtnRow">
                    <button type="button" class="btnSetting">
                        <img src="{% static 'images/main/inCameraBtn.png' %}" width="100px" height="100px" />
                    </button>
                </div>
                <div class="schemeOutCameraBtnRow">
                   <button type="button" class="btnSetting">
                       <img src="{% static 'images/main/outCameraBtn.png' %}" width="100px" height="100px" />
                   </button> 
                </div>
            </div>
            <hr size="2" width="100%" color="black">
            <div class="insertIdContainer">
                <div class="insertIdRow">
                    <input type="text" size="20px" />
                    Filter Id 입력 부분
                </div>
            </div>
            <div class="contentsListContainer">
                필터 리스트 노출 영역
                <div class="categoryNameColumn">
                    카테고리 이름 노출 영역
                </div>
                <div class="showContentsContainer">
                    <div class="contentsIdColumn">
                        <컨텐츠 ID 노출 영역>
                    </div>
                    <div class="contentsThumbnailColumn">
                        컨텐츠 썸네일 노출 영역
                    </div>
                    <div class="contentsNameColumn">
                        <컨텐츠 이름 노출 영역>
                    </div>
                </div>
            </div>
        </div>
    <script>
    $(function(){
        console.log('tt');
        filterArgs.mainUrl = '{{ app }}' + '://go?filterId='
        $("#scheme_input").val(filterArgs.mainUrl);
    })
    </script>
{% endblock %}

templates/soda_beta/helper_main.html
{# 반복되는 html 태그를 base.html에 작성한 뒤에 다른 html문서에서 상속받는 방법으로 반복되는 코드를 줄일 수 있다.#}
{% extends 'base.html' %}
{# 정적파일 분석하기 #}
{% load static %}
{# 템플릿 상속 : https://docs.djangoproject.com/en/2.1/ref/templates/language/#template-inheritance  #}
{% block main %}


     <link rel="stylesheet" href="{% static 'css/main/helper_main.css' %}">

     <link rel="stylesheet" href="{% static 'css/helper_filter.css' %}">
     <link rel="stylesheet" href="{% static 'css/helper_studio.css' %}">
<script src="{% static 'js/main/helper_main.js' %}"></script>



        <div class="pageTitle">
            SODA/Tianyan QAHelper
        </div>
        <div class="schemeContainer">
            <div class="appSelectTitle">Select App</div>
            <div class="appIconContainer">
                <div class="sodaRealAppIconRow">
                    <input data-app="soda" type="image" src="{% static 'images/main/sodaIconReal.png' %}" width="100px" height="100px" class="iconRound" />
                </div>
                <div class="sodaBetaAppIconRow">
                    <input data-app="sodab" type="image" src="{% static 'images/main/sodaIconBeta.png' %}" width="100px" height="100px" class="iconRound" />
                </div>
                <div class="tianyanRealAppIconRow">
                    <input data-app="tianyan" type="image" src="{% static 'images/main/tianyanIconReal.png' %}" width="100px" height="100px" class="iconRound" />
                </div>
                <div class="tianyanBetaAppIconRow">
                    <input data-app="tianyanb" type="image" src="{% static 'images/main/tianyanIconBeta.png' %}" width="100px" height="100px" class="iconRound" />
                </div>
            </div>
            <div class="schemeTitle">Scheme</div>
            <div class="schemeItemContainer">
                <div class="schemeStyleBtnRow">
                    <button type="button" class="btnSetting">
                        <a href="javascript:void(0)" onclick="click_scheme('style')"><img src="{% static 'images/main/styleIcon.png' %}" width="100px" height="100px"></a>
                    </button>
                </div>
                <div class="schemeFilterBtnRow">
                    <button type="button" class="btnSetting">
                        <!--<a href="./helper_filter.html"><img src="{% static 'images/main/filterIcon.png' %}" width="100px" height="100px"></a> -->
                        <a href="javascript:void(0)" onclick="click_scheme('filter')"><img src="{% static 'images/main/filterIcon.png' %}" width="100px" height="100px"></a>
                    </button>
                </div>
                <div class="schemeStudioBtnRow">
                    <button type="button" class="btnSetting">
                        <a href="./helper_studio.html"><img src="{% static 'images/main/studioIcon.png' %}" width="100px" height="100px"></a>
                    </button>
                </div>
            </div>
        </div>

    <script>

    </script>
{% endblock %}

templates/soda_beta/helper_style.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <link rel="stylesheet" href="{% static 'css/scheme/helper_style.css' %}">
    <script src="{% static 'js/scheme/helper_style.js' %}"></script>
    <div class="pageTitle">
        SODA/Tianyan QAHelper
    </div>
    <div class="mainContainer">
        <div class="mainTitle">
            Style
        </div>
        <div class="showSchemeContainer">
            <div class="showSchemeRow">
                <input type="text" size="150px" id="scheme_input"/>
                현재 스킴 실시간 보여주는 영역
            </div>
            <div class="qrcodeRow">
                <button type="button">
                    QR Code
                </button>
            </div>
        </div>
        <div class="showQrcodeColumn">
            <!-- QR Code 들어오는 자리 -->
            <img src="./qr_ex.png" width="200px" height="200px">
        </div>
        <hr size="2" width="100%" color="black">
        <div class="schemeListContainer">
            <div class="schemeAutoDlBtnRow">
                <button type="button" class="btnSetting1" auto="true">
                    <img src="{% static 'images/main/autoDlBtn.png' %}" width="100px" height="100px"/>
                </button>
            </div>
            <div class="schemeManualDlBtnRow">
                <button type="button" class="btnSetting1" auto="false">
                    <img src="{% static 'images/main/manualDlBtn.png' %}" width="100px" height="100px"/>
                </button>
            </div>
            <div class="schemeInCameraBtnRow">
                <button type="button" class="btnSetting2" position="0">
                    <img src="{% static 'images/main/inCameraBtn.png' %}" width="100px" height="100px"/>
                </button>
            </div>
            <div class="schemeOutCameraBtnRow">
                <button type="button" class="btnSetting2" position="1">
                    <img src="{% static 'images/main/outCameraBtn.png' %}" width="100px" height="100px"/>
                </button>
            </div>
        </div>
        <hr size="2" width="100%" color="black">
        <div class="insertIdContainer">
            <div class="insertIdRow">
                <input type="text" size="20px"/>
                Style Id 입력 부분
            </div>
        </div>
        <div class="content-main">
        <div class="contentsListContainer">
            <div class="categoryNameColumn">
                카테고리 이름 노출 영역
            </div>


            <div class="showContentsContainer-div">
                <div class="showContentsContainer">
                    <div class="contentsIdColumn">
                        <컨텐츠 ID 노출 영역>
                    </div>
                    <div class="contentsThumbnailColumn">
                        컨텐츠 썸네일 노출 영역
                    </div>
                    <div class="contentsNameColumn">
                        <컨텐츠 이름 노출 영역>
                    </div>
                </div>
                <div class="showContentsContainer">
                    <div class="contentsIdColumn">
                        <컨텐츠 ID 노출 영역>
                    </div>
                    <div class="contentsThumbnailColumn">
                        컨텐츠 썸네일 노출 영역
                    </div>
                    <div class="contentsNameColumn">
                        <컨텐츠 이름 노출 영역>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
    <script>
        $(function () {
            console.log('tt');
            styleArgs.mainUrl = '{{ app }}' + '://go?';
            set_main_url();
        })
    </script>
{% endblock %}

templates/soda_beta/soda_main.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <link rel="stylesheet" href="{% static 'css/soda_beta.css' %}">

    <div class="title">Soda</div>
    <div class="soda-menus">
        <div class="soda-menu"><a href="{% url 'soda_beta:qa_helper' type='soda' %}">SCHEME</a></div>
        <div class="soda-menu">Style</div>
    </div>

      <div class="title">SodaBeta</div>
    <div class="soda-menus">
        <div class="soda-menu"><a>SCHEME</a></div>
        <div class="soda-menu">Style</div>
    </div>
      <div class="title">Tianyan</div>
    <div class="soda-menus">
        <div class="soda-menu"><a>SCHEME</a></div>
        <div class="soda-menu">Style</div>
    </div>
      <div class="title">TianyanBeta</div>
    <div class="soda-menus">
        <div class="soda-menu"><a>SCHEME</a></div>
        <div class="soda-menu">Style</div>
    </div>
{% endblock %}